### ISSUE TITLE
Task: figure out what level of permission every device in the network needs.

### ISSUE THREAD

**Issue by karppa404** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#15]
[User Story #4](https://github.com/orgs/Allen-ISD-Computer-Science/projects/9/views/2?pane=issue&itemId=46664948)

**Comment by Fangedan** [comment]
According to the draw.io Jacob published ([https://raw.githubusercontent.com/Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024/626f6df6faede8fd93b05785e1fb1c22017d755b/MoonBaseNetwork.drawio%20(1).png](url)):


![Image](https://github.com/Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024/assets/89644316/fe24feca-0233-477e-82ba-ef0e96ffb2d0)

The levels of permissions for NASA EOSDIS data products range from level 0 to level 4:
| **Data Level** | **Description** |
|--------|--------|
| Level 0 | Reconstructed, unprocessed instrument and payload data at full resolution, with any and all communications artifacts (e.g., synchronization frames, communications headers, duplicate data) removed. (In most cases, NASA's EOS Data and Operations System [EDOS] provides these data to the DAACs as production data sets for processing by the Science Data Processing Segment [SDPS] or by one of the SIPS to produce higher-level products.) **_Completely unprocessed instrument, no security with only payload data._** |
| Level 1 | Level 1 data are reconstructed, unprocessed instrument data at full resolution, time-referenced, and annotated with ancillary information, including radiometric and geometric calibration coefficients and georeferencing parameters (e.g., platform ephemeris) computed and appended but not applied to L0 data. L1 data includes new variables to describe the spectra. These variables allow the user to identify which L1 channels have been copied directly from other L1 channels and which have been synthesized from them and why. **_Basically the raw data with no filters, available for encryption/decryption, vulnerable._** |
| Level 2 | L2 data contains information derived from the geolocated sensor data, such as ground elevation, highest and lowest surface return elevations, energy quantile heights (“relative height” metrics), and other waveform-derived metrics describing the intercepted surface. **_The permission layer where information about the raw data is processed, and communicated within the level._** |
| Level 3 | Variables mapped on uniform space-time grid scales, usually with some completeness and consistency. L3 data are generally periodic summaries (weekly, ten-day, monthly) of L2 products. **_Encrypted data, sends key._** |
| Level 4 | Model output or results from analyses of lower-level data (e.g., variables derived from multiple measurements). **_Decrypted data, receives key._** | 

The levels of permissions of each device in the top right corner should be (subject to change/discussion):

1. Radar Dish - _**Level 0, 1, and 2**_
2. Individual Computers - _**Level 0 and 1**_
3. Base Switch - _**Level 0, 1, and 2**_
4. Base Router - _**Level 3 and 4**_
5. Radio Tower - _**Level 3 and 4**_
6. Base Server - _**Level 3 and 4**_

> Source: [https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-information-policy/data-levels](url)
