### ISSUE TITLE
Task: slide show template

### ISSUE THREAD

**Issue by abelSemahegn** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#25]
Find a slide show theme to help explain our project.
Suports Story: #2

**Comment by ditya-beta** [comment]
https://docs.google.com/presentation/d/1hnKhyBPK7oiin_4c35e8yQ7MR_b7rczlEB2W8qS2RWo/edit?usp=sharing

**Comment by ditya-beta** [comment]
Chosen theme here
https://drive.google.com/file/d/1A1fHuk4vmf2Bxw6n9y58xqLA05FoBFgi/view?usp=sharing
