### ISSUE TITLE
Task: sketch of interactive website

### ISSUE THREAD

**Issue by abelSemahegn** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#29]
We Need an interactive website to guide visitors through our moon base satellites, and earth Headquarters.
Supports Story: #10 #28

**Comment by s-sannidhi** [comment]
Here is a link to the rough draft of how our interactive website will function: [https://drive.google.com/file/d/1WzUJuC2ZeQK8iq3TUBlkxeuN_UDbkqqW/view?usp=sharing](https://drive.google.com/file/d/1WzUJuC2ZeQK8iq3TUBlkxeuN_UDbkqqW/view?usp=sharing)

**Comment by abelSemahegn** [comment]
Looks a-ok!!!!
