### ISSUE TITLE
Task: ArtStation Background Assets

### ISSUE THREAD

**Issue by abelSemahegn** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#34]
Go to [Art Station](https://www.artstation.com/?sort_by=community&dimension=all), and assemble what we need. This could be:
Lunar landscapes
moon bases
astronoutes
space ships

Make sure to document on work cited.
Supports Story: #28

**Comment by ditya-beta** [comment]
[All of the assets we have found](https://docs.google.com/document/d/1RDqScbVDDUQ2l0LMvi1Kkg3uVPESdbiN8vvtXm-Zuh0/edit?usp=sharing)
