### ISSUE TITLE
Task: Diagram

### ISSUE THREAD

**Issue by stuffysaturn** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#39]
Visually demonstrate the protocol that transfers files between systems. This diagram should be self explanatory to people who do not have a deep understanding of computer science topics.

Supports Story: #38

**Comment by Fangedan** [comment]
I have completed the presentation that not only outlines the file transfer between systems but will also be adequate enough to present to possible representatives. Here is the google slides link:

https://docs.google.com/presentation/d/1yy5wZxm44n5CV3NfuLQcmYtim-0MNsef_eiQNs5aADA/edit?usp=sharing
