### ISSUE TITLE
Task: Physical Product Demonstration 1

### ISSUE THREAD

**Issue by Richard-Jang** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#40]
We need a physical demonstration of systems sending files between each other with a visual representation of the network traffic and encryption method. From Tuesday to Wednesday, research and learning.

- P2P Networks
- Web Sockets
- Hardware (2 raspberry PI, 2 ethernet, 2 monitors, 1 switch)
- Front End (displays status of files)

Supports Story: #38

**Comment by abelSemahegn** [comment]
This did not happen due to the pi 3's speed
