### ISSUE TITLE
Task: Familiarize Photon Probability Formula

### ISSUE THREAD

**Issue by Fangedan** [Allen-ISD-Computer-Science/REPO_NASA_CybSec_2024#62]
Read up on this Wikipedia article: [https://en.wikipedia.org/wiki/Quantum_key_distribution](url)

Understand details surrounding Quantum Distribution of Keys and mathematical formula(s) for calculating probability of success (photon entanglement/collision).

**Comment by Fangedan** [comment]
https://docs.google.com/document/d/1WiChLgCpImti4AcLJszmrM9jA6iNXV4nUs9cNuuiYJc/edit?usp=sharing

**Comment by abelSemahegn** [comment]
not realistic
